In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
sentences = [
    "The glass of milk",
    "The glass of juice",
    "The cup of Tea",
    "I am a good boy",
    "I am a Student",
    "I make AI Projects"
]

##Define the Vocabulary Size

In [3]:
vocab_size = 10000 ##vocabulary size

one_hot_repre = [one_hot(words,vocab_size) for words in sentences] ##One Hot Representation (it takes 2D array to make a one hot representation)

one_hot_repre

[[7, 2892, 8917, 4284],
 [7, 2892, 8917, 6715],
 [7, 6413, 8917, 237],
 [3548, 9420, 4991, 5591, 2716],
 [3548, 9420, 4991, 9496],
 [3548, 3374, 450, 972]]

# Each word is converted into a number in one hot representation 

# Word Embedding Representation

In [11]:
import tensorflow as tf
import keras
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_len = 8 ##sentence length (hypothetical)

emb_docs = pad_sequences(one_hot_repre,padding = 'pre',maxlen=sent_len) ##padding (basically making all the sentences have same no. of words)

print(emb_docs)

[[   0    0    0    0    7 2892 8917 4284]
 [   0    0    0    0    7 2892 8917 6715]
 [   0    0    0    0    7 6413 8917  237]
 [   0    0    0 3548 9420 4991 5591 2716]
 [   0    0    0    0 3548 9420 4991 9496]
 [   0    0    0    0 3548 3374  450  972]]


feature representation

In [10]:
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_len))
model.compile('adam','mse')
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(emb_docs)

1/1 [==============================] - 0s 23ms/step


array([[[-1.32159814e-02,  2.36892961e-02, -3.59982140e-02,
          3.27770375e-02, -5.34369797e-03, -2.53934786e-03,
          3.54832299e-02, -3.94292958e-02,  4.71695997e-02,
         -6.36810064e-03],
        [-1.32159814e-02,  2.36892961e-02, -3.59982140e-02,
          3.27770375e-02, -5.34369797e-03, -2.53934786e-03,
          3.54832299e-02, -3.94292958e-02,  4.71695997e-02,
         -6.36810064e-03],
        [-1.32159814e-02,  2.36892961e-02, -3.59982140e-02,
          3.27770375e-02, -5.34369797e-03, -2.53934786e-03,
          3.54832299e-02, -3.94292958e-02,  4.71695997e-02,
         -6.36810064e-03],
        [-1.32159814e-02,  2.36892961e-02, -3.59982140e-02,
          3.27770375e-02, -5.34369797e-03, -2.53934786e-03,
          3.54832299e-02, -3.94292958e-02,  4.71695997e-02,
         -6.36810064e-03],
        [ 3.02078575e-03, -1.29287615e-02, -1.44239888e-02,
          3.89980115e-02, -1.20115280e-02,  3.40915807e-02,
         -3.14458497e-02, -1.76605359e-02,  8.601367